MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker/Storyboards/UnsubmittedAssignmentViewController.storyboard
MusicMaker/MusicMaker/View Controllers/UnsubmittedAssignmentViewController.swift
MusicMaker/MusicMaker/Views/AssignmentInstructionsTableViewCell.swift

I added an instructions cell to the table view, and I tested it with some texts I created. 
- [x New feature (non-breaking change which adds functionality)
I passed in some texts and ran this on the simulator to see how it looked. I also fixed some constraints along the way to allow the texts to fit better on screen.

iOS Assignment Instructions Table View Cell

---

netlify.toml

Set up build file for CI with Netlify.
https://trello.com/c/rGdBrAb3/80-deploy-frontend

Set up build file for CI with Netlify.

---

client/src/views/dashboardBillingView.js

This pull request should fix the syntax error issues.

Syntax error in dashboardBillingView.js causing Netlify errors.

---

client/src/components/App.js
client/src/components/DashboardNavigation.js
client/src/components/SideBar.js
client/src/constants/routes.js
client/src/views/dashboardView.js
client/src/views/landingView.js
client/src/views/studentListView.js
server/.gitignore

This PR is based on two previous PR that were not able to be merged due to Netlify issues, I retested that everything worked how it should.
https://github.com/Lambda-School-Labs/Labs8-MusicMaker/pull/37
Made a teacher dashboard skeleton with no CSS. I did not delete the previous code, I commented it out in case the majority of the group doesn't agree with my changes. If you want to see how the pages would work let me know and I can show you from my end.
https://github.com/Lambda-School-Labs/Labs8-MusicMaker/pull/38
Added what studentListView.js will render which is a list of students with the students' names, instruments, and level. I added DashboardNavigation and SideBar commented out because it has not been merged to master yet from the previous PR containing teacher's dashboard …

Teacher Dashboard Skeleton & Student List View - Frontend

---

MusicMaker/MusicMaker/View Controllers/RecordingViewController.swift

Adds ability to drag the video so students can move the video recording around the screen

Ios assignment ui videodragging

---

MusicMaker/MusicMaker/Storyboards/UnsubmittedAssignmentViewController.storyboard
MusicMaker/MusicMaker/View Controllers/RecordingViewController.swift
MusicMaker/MusicMaker/View Controllers/UnsubmittedAssignmentViewController.swift
MusicMaker/MusicMaker/Views/AssignmentMusicPieceTableViewCell.swift
MusicMaker/MusicMaker/Views/MusicSheetPageCollectionViewCell.swift

Fixed the PDF thumbnails and previews so that they are not cropped off in the collection view cell or when the screen is resized. 
- [] Bug fix (non-breaking change which fixes an issue)
Ran this on my iPad to make sure it works correctly.

iOS Assignment UI PDF Resize

---

server/server.js

In this api endpoint, the teacher should be able to get their settings info: email and name.
api structure: /teacher/:idTeacher/settings
Test Sample: http://localhost:8000/teacher/AHnU7PuWMohJWEWZJbvd/settings

Backend: Teacher GET their Settings

---

MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker/Model Controllers/MusicMakerModelController.swift
MusicMaker/MusicMaker/Models/Assignment+Convenience.swift
MusicMaker/MusicMaker/Models/CoreData.swift
MusicMaker/MusicMaker/Models/MusicMakerModel.xcdatamodeld/MusicMakerModel.xcdatamodel/contents
MusicMaker/MusicMaker/Models/Teacher+Convenience.swift
MusicMaker/MusicMaker/View Controllers/UnsubmittedAssignmentViewController.swift

Added basic skeleton for core data.
- [] Bug fix (non-breaking change which fixes an issue)
I tested this by creating a dummy teacher/assignment when the app first launches, then I commented out the dummy sample and check it core data still has it.

iOS Core Data Part 1

---

MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker.xcodeproj/xcshareddata/xcschemes/MusicMaker.xcscheme
MusicMaker/MusicMaker/Models/Assignment+Convenience.swift
MusicMaker/MusicMaker/View Controllers/RecordingViewController.swift
MusicMaker/MusicMaker/View Controllers/UnsubmittedAssignmentViewController.swift
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/BoringSSL.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/FirebaseAuth.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/FirebaseCore.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/FirebaseFirestore.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/FirebaseStorage.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/GTMOAuth2.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/GTMSessionFetcher.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/GoogleToolboxForMac.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/GoogleUtilities.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-MusicMaker.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Protobuf.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC-C++.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC-Core.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC-ProtoRPC.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC-RxLibrary.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC-gRPCCertificates.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/gRPC.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/leveldb-library.xcscheme
MusicMaker/Pods/Pods.xcodeproj/xcshareddata/xcschemes/nanopb.xcscheme

I added local recording URL management to assignment so recordings can be saved locally on the device when the user is working on the assignment and is not ready to submit yet. At this stage, videos can be recorded, saved, and played back. The user can also re-record and the playback view will be updated with the new recording. The only issue at this point is there is no audio in the recording.
I tested this feature by running it on my iPad and recording some sample. Playback view is automatically updated with the recording when I dismissed the recording screen, and the playback plays smoothly. The screen resized nicely when used in dual app orientation.

iOS Core Data Part 2 (VideoRecording/Playback)

---

client/src/css/index.css
client/src/less/createAssignmentView.less
client/src/less/dashboardAssignmentsView.less
client/src/less/dashboardBillingView.less
client/src/less/dashboardSettingView.less
client/src/less/dashboardView.less
client/src/less/index.less
client/src/less/studentListView.less
client/src/views/createAssignmentView.js
client/src/views/dashboardAssignmentsView.js
client/src/views/dashboardBillingView.js
client/src/views/dashboardSettingView.js
client/src/views/dashboardView.js
client/src/views/studentListView.js

Updated basic skeleton styles for all teacher dashboard views.
https://trello.com/c/kPQ7cQTd/125-finish-basic-styles-for-teacher-dashboard-subpages

Completed teacher skeleton styles.

---

MusicMaker/MusicMaker/Model Controllers/MusicMakerModelController.swift
MusicMaker/MusicMaker/Models/Assignment+Convenience.swift
MusicMaker/MusicMaker/Models/MusicMakerModel.xcdatamodeld/MusicMakerModel.xcdatamodel/contents
MusicMaker/MusicMaker/Models/Teacher+Convenience.swift

I implemented the model controller to fetch the teachers and assignments from the server.
I tested this feature by calling the method and checking the results in the console. If there is not data, there the console will log the errors.

iOS Model Basic Fetch

---

MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker/Storyboards/SplitView.storyboard
MusicMaker/MusicMaker/Storyboards/SubmittedAssignmentViewController.storyboard
MusicMaker/MusicMaker/View Controllers/SubmittedAssignmentViewController.swift
MusicMaker/MusicMaker/Views/AssignmentInstructionsTableViewCell.swift

I added a submitted assignment view, and this screen will show the details about the assignment and the feedback from the teacher. It is not the same as the un-submitted assignment view because when the assignment is already submitted, it wouldn't have things like a record button or a submit button. The submitted assignment view is only for viewing results and the user cannot add or modify it.
I tested this feature by building it on my iPad and checking to see if everything was in order.

iOS Submitted Assignment

---

client/src/components/StripeFrontend.js
server/functions/index.js

Got the frontend and backend of Stripe working together on Localhost. I've changed the routes so they should work with deployed version.
Test A - Ran via localhost, button appears.
Test B - Clicked via localhost, Stripe modal pops up with info to be filled in.
Test C - Final test will be with firebase deployment after merge.

Fixed path to work while deployed and removed unnecessary code.

---

server/functions/index.js

This api endpoint, gives a teacher a list of their students with the student's email, name,  level, and instrument.

Teacher can GET a list of students with the student's info

---

server/functions/index.js

GET endpoints: list of students assigned to a teacher, individual student, student's completed assignment to be fetched for grading.
https://trello.com/c/yOJlytxe/131-teacher-get-a-list-of-students-names-instrument-and-level
https://trello.com/c/3MoNCftT/149-teacher-get-individual-student
https://trello.com/c/hxreetGX/150-teacher-get-list-of-students-assignments

Completed endpoints for remaining teacher GETs

---

server/functions/index.js
server/functions/package.json
server/functions/yarn.lock

** PLEASE DO NOT MERGE THIS YET **

Adding new QR signup code after backend redeployment.

---

MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker/Storyboards/SubmittedAssignmentViewController.storyboard
MusicMaker/MusicMaker/View Controllers/MusicSheetPDFSingleViewController.swift
MusicMaker/MusicMaker/View Controllers/SubmittedAssignmentViewController.swift

Added a music sheet pdf single page view so that when the user taps on the pdf thumbnail on the submitted assignment view controller, it will show the single page in full screen.
I tested this on my iPad.

iOS Assignment UI PDF Single Page View

---

MusicMaker/MusicMaker/Model Controllers/MusicMakerModelController.swift
MusicMaker/MusicMaker/View Controllers/AssignmentsViewController.swift
MusicMaker/MusicMaker/View Controllers/TeachersViewController.swift

Added Firestore listeners to teachers and assignments so when there is a change in the database, the model can be updated.
Tested this on my iPad.

iOS Model Update

---

netlify.toml

Updated toml file to prevent issues with deployed version refusing to refresh pages.
Can only be tested by deploying.

This should fix the refresh 404 issues on Netlify deploy

---

client/src/views/dashboardAssignmentsView.js

Created files to start implementing assignment cards. Fixed some styling and added back in example assignment in case things aren't implemented in time for today.
Locally.

Fixed styling and added in files to make cards with.

---

client/src/views/signupView.js

Adds a basic presentation layout for the signup form.
Ran locally in multiple browsers to test for responsiveness.

Added basic signup page styling and layout.

---

client/src/views/dashboardAssignmentsView.js
client/src/views/dashboardView.js

- Added a container to center the page.
- Normalized font sizes and weights.
Locally.

Improved styling of dashboard.

---

client/src/views/dashboardBillingView.js

- Added a container to center the page.
Locally.

Billing page tweaks

---

MusicMaker/MusicMaker/Models/Assignment+Convenience.swift
MusicMaker/MusicMaker/Models/MusicMakerModel.xcdatamodeld/MusicMakerModel.xcdatamodel/contents
MusicMaker/MusicMaker/Storyboards/AssignmentsTableViewController.storyboard
MusicMaker/MusicMaker/View Controllers/AssignmentsTableViewController.swift
MusicMaker/MusicMaker/Views/AssignmentTableViewCell.swift

Added sections to the assignments table view controller so the assignments can be sorted according to whether or not it is submitted and also by due dates, with the earliest due date at the top.
Tested on my device.

iOS Assignment Cell Update

---

client/src/views/createAssignmentView.js

***WIP***
- Added a container to center the page.
Locally.

Added a container around the page.

---

client/src/views/createAssignmentView.js
client/src/views/dashboardView.js
client/src/views/gradeAssignmentView.js
client/src/views/studentListView.js

Teacher  will be able to see a list of their students.

Frontend: Student List View with Basic CSS

---

client/package.json
client/src/components/Navigation.js
client/src/components/SignOutButton.js
client/src/components/withAuthentication.js
client/src/firebase/auth.js
client/src/views/signinView.js
client/src/views/signupView.js

- Added redirects on signin/signout.
- Cleaned up unnecessary code
Locally.

Fix redirects on signin/signout

---

client/src/components/App.js
client/src/components/PaidUserContext.js
client/src/components/withPayment.js

- Created a HOC to check if a user is paid. Protects routes if not paid.
- Tested by manually changing the subscribed bool in the test user.

Created a HOC that protects certain routes from non-paid users. Currently wrapped around grading, needs wrapped around assigning.

---

client/src/components/App.js
client/src/components/withAuthentication.js

- Updated auth HOC. Protects routes if not auth.
- Tested on localhost.

Edited auth HOC to protect routes.

---

client/src/components/App.js
client/src/components/Navigation.js
client/src/components/withAuthentication.js
client/src/components/withPayment.js

- Fixed bug with nav not re-rendering based on authentication.
- The withAuthentication HOC was interacting strangely when applied to individual components instead of the App component. Slightly refactored to resolve.
- Tested on localhost.
- Jeanette pair programmed.

Refactored redirecting code a bit to resolve a bug with nav not rendering.

---

client/src/components/UpdateName.js
client/src/views/dashboardSettingView.js

Teacher's settings page now displays information properly and has a look consistent with the rest of the application. An UpdateNote component has been created and will be worked on in the next PR to allow teachers to change their name from the dashboard's settings page.
Tested locally in multiple browsers and on iPhone.

Updated dashboard settings page to display teacher information correctly and styled it in a manner consistent with other views.

---

client/src/views/dashboardAssignmentsView.js
server/functions/index.js

This page will allow teachers to see a list of all their ungraded assignments.

Frontend: Teachers can see a card of all of their ungraded assignments

---

MusicMaker/MusicMaker/Supporting Files/Info.plist

Changed build number to 2.
N/A

iOS Changed build number to 2

---

client/src/components/App.js
client/src/components/SideBar.js
client/src/constants/routes.js
client/src/views/assignmentStudentsView.js
client/src/views/dashboardAssignmentsView.js
client/src/views/studentListView.js
server/functions/index.js

//Assignment's Students List: After clicking on an assignment from dashboardAssigmentsView.js,
//it'll take you to another page with "+" to add student's to an assignment, 
//click assignment's name to see the full ungraded assignment (optional)
//click on student to see student's assignment submission for grading.

Frontend: Teacher can see a list of students under an assignment

---

MusicMaker/MusicMaker.xcodeproj/project.pbxproj
MusicMaker/MusicMaker/Supporting Files/GoogleService-Info.plist
MusicMaker/MusicMaker/Supporting Files/Info.plist

Fixed google plist
Tested on device

Fix google plist

---

client/src/views/signupView.js
server/functions/index.js

- Set up POST to DB with teacher details on signup.
WIP

Teacher account creation post

---

client/src/views/landingView.js
client/src/views/signinView.js
client/src/views/signupView.js

- Updated Landing Page copy.
- Updated Landing Page button to redirect to signup.
- Updated auth pages to say Teacher Signin/up.
Locally tested. These are just visual changes.

Updated copy on landing page and button links to sign up. Updated signup/in to specify Teacher.

---

client/src/components/UpdateName.js
client/src/views/dashboardSettingView.js

Added a settings update function for teachers, available from their dashboard "settings" page.
Tested locally multiple times across different browsers.

Adding functionality to allow teacher to change settings from their dashboard page.

---

client/src/components/SideBar.js
client/src/components/StripeFrontend.js
client/src/views/assignmentStudentsView.js
client/src/views/createAssignmentView.js
client/src/views/dashboardAssignmentsView.js
client/src/views/dashboardBillingView.js
client/src/views/dashboardSettingView.js
client/src/views/dashboardView.js
client/src/views/studentAssignmentsView.js
client/src/views/studentListView.js

As described in PR message, normalizes a user's views throughout all current pages of the app.
Tested locally in multiple browsers.

Normalized view styling for all current pages. Billing and teacher settings edit forms need some more work, but basic layout is complete.

---

client/src/views/assignmentStudentsView.js
client/src/views/createAssignmentView.js
client/src/views/dashboardAssignmentsView.js
client/src/views/dashboardSettingView.js
client/src/views/dashboardView.js
client/src/views/gradeAssignmentView.js
client/src/views/signupView.js
client/src/views/studentAssignmentsView.js
client/src/views/studentListView.js

When a user is created, they're now saved by their authentication uid instead of a random id.

Successfully made it so new users are saved by their uid instead of a random id.

---

client/src/views/assignmentStudentsView.js
client/src/views/gradeAssignmentView.js
server/functions/index.js

//Grade Assignment View: This page will let teacher's see a student's assignment both completed and not completed.
//When the assignment is completed the teacher can see the assignment information and the students video to be able to 
//give the student feedback and a grade(Passed/Failed).Fixes # (issue)

Frontend - Teacher Grading View is set Dynamically
